version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=sqlite:///./dev.db
    # Remove volume in production unless you need live code sync
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:80' # Host:Container
    command: npx serve -s dist -l 80
    # Remove volume in production
    # volumes:
    #   - ./frontend:/app
